force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProjectPage.cls
public class ProjectPage {
    @AuraEnabled
    public static List<Project__c> AllProjects(){
         return [SELECT Id, Name FROM Project__c]; 
    }
    
    @AuraEnabled
    public static Employee__c  getEmployeeProject(String employeeId){
        Employee__c emp=[Select Id,Project__r.Name,Project__c FROM Employee__c WHERE Id=:employeeId LIMIT 1];
        if (emp != null && emp.Project__c == null) {
             throw new AuraHandledException('Record not found.');
        } 
        return emp;
         
    }
    
    @AuraEnabled
    public static void updateproject(String employeeId,String projectId){
        Employee__c pr=[Select Id,Project__c FROM Employee__c WHERE Id=:employeeId LIMIT 1];
        pr.Project__c=projectId;
        update pr;
    }

}