force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Software Engineer</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>20</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Phone_No__c.field-meta.xml
<CustomField>
    <fullName>Phone_No__c</fullName>
    <label>Phone No</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Interviewer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/registerPage.cls
public with sharing class registerPage {
    @AuraEnabled
    public static void register(String user, 
                              String pass, 
                              String emailid, 
                              String Nam, 
                              String Add,
                              String Depart, 
                              String DOb,
                              String phon,
                              String userty) {
        // Check if username already exists
        
        Date dobDate = Date.valueOf(DOb);
        //Integer existing = [SELECT COUNT() FROM Employee__c WHERE Username__c = :username];
        //if (existing > 0) {
          //  throw new AuraHandledException('Username already exists.');
        //}
        
        Employee__c newEmployee = new Employee__c();
            newEmployee.Username__c = user;
            newEmployee.Password__c = pass; // Replace with hashed password
            newEmployee.Email__c = emailid;
            newEmployee.Name = Nam;
            newEmployee.Phone_No__c=phon;
            newEmployee.User_Type__c=userty;

            if (!String.isBlank(Add)){
              newEmployee.Address__c=Add;
            }

            if (!String.isBlank(DOb)){
              newEmployee.DOB__c=dobDate;
            }

            if (!String.isBlank(Depart)){
              newEmployee.Department__c=Depart;
            }


            
            insert newEmployee;
            //return newEmployee.Id;
    }

}