force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave__c/Leave__c.object-meta.xml
<CustomObject>
    <label>Leave</label>
    <nameField>
        <label>leave Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leaves</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Leaves</relationshipLabel>
    <relationshipName>Leaves</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Leave__c/fields/Leave_Type__c.field-meta.xml
<CustomField>
    <fullName>Leave_Type__c</fullName>
    <label>Leave Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casual Leave</fullName>
            </value>
            <value>
                <fullName>Unpaid Leave</fullName>
            </value>
            <value>
                <fullName>Halfday Leave</fullName>
            </value>
            <value>
                <fullName>Short Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave__c/fields/Reason_for_leave__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_leave__c</fullName>
    <label>Reason for leave</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApplyLeavePage.cls
public class ApplyLeavePage {
    @AuraEnabled
    public static void leaverequest(string start,string enddat,string leavereason,string leavetype,String employeeId,String email){
        Date startdate = Date.valueOf(start);
        Date enddate = Date.valueOf(enddat);
        Employee__c employee = [SELECT Id FROM Employee__c WHERE Id = :employeeId LIMIT 1];
           Leave__c newleave=new Leave__c();
           newleave.Start_Date__c=startdate;
           newleave.End_Date__c=enddate;
           newleave.Reason_for_leave__c=leavereason;
           newLeave.Employee_Name__c = employee.Id;
           newLeave.Employee_Email__c=email;
           newLeave.Status__c='Pending';
           newLeave.Leave_Type__c=leavetype;

        
        insert newleave;
        
    }

    @AuraEnabled(cacheable=true)
    public static String getEmployeeEmail(Id userId) {
        Employee__c emp = [SELECT Email__c FROM Employee__c WHERE Id = :userId LIMIT 1];
        return emp.Email__c;
    

}
}