force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/IS_Clicked__c.field-meta.xml
<CustomField>
    <fullName>IS_Clicked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IS Clicked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Clicked_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Clicked_Date__c</fullName>
    <label>Last Clicked Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/UpdateClicked.cls
global class UpdateClicked implements Schedulable {
    global void execute(SchedulableContext context) {
        DateTime sevenDaysAgo = System.now().addDays(-7);
        
        List<Employee__c> employeesToUpdate = [SELECT Id FROM Employee__c 
                                                WHERE Last_Clicked_Date__c < :sevenDaysAgo OR Last_Clicked_Date__c = null];

        for (Employee__c employee : employeesToUpdate) {
            employee.Is_Clicked__c = false; // Set Is_Clicked__c to true if not clicked for 7 days
        }

        if (!employeesToUpdate.isEmpty()) {
            update employeesToUpdate;
        }
    }
}