force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <label>Applicant Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/JobAdvertisement__c.field-meta.xml
<CustomField>
    <fullName>JobAdvertisement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>JobAdvertisement</label>
    <referenceTo>JobAdvertisement__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobAdvertisement__c/JobAdvertisement__c.object-meta.xml
<CustomObject>
    <label>JobAdvertisement</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>JobAdvertisement  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JobAdvertisements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/JobAdvertisement__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobNotificationQueueable.cls
public class JobNotificationQueueable
implements Queueable {

    private Id applicationId;

    public JobNotificationQueueable(
        Id appId
    ) {

        this.applicationId = appId;
    }

    public void execute(
        QueueableContext qc
    ) {

        Application__c app = [

            SELECT Id,
                   Applicant_Name__c,
                   Email_ID__c,
                   JobAdvertisement__r.Job_Title__c
            FROM Application__c
            WHERE Id = :applicationId
            LIMIT 1
        ];

        Messaging.SingleEmailMessage mail =
            new Messaging.SingleEmailMessage();

        mail.setToAddresses(
            new List<String>{
                app.Email_ID__c
            }
        );

        mail.setSubject(
            'Application Submitted'
        );

        mail.setPlainTextBody(

            'Hello ' +
            app.Applicant_Name__c +
            ', your application for "' +
            app.JobAdvertisement__r.Job_Title__c +
            '" has been submitted successfully.'
        );

        Messaging.sendEmail(
            new List<Messaging.SingleEmailMessage>{
                mail
            }
        );
    }
}