force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <label>Applicant Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/JobAdvertisement__c.field-meta.xml
<CustomField>
    <fullName>JobAdvertisement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>JobAdvertisement</label>
    <referenceTo>JobAdvertisement__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>1st Round</fullName>
            </value>
            <value>
                <fullName>2nd Round</fullName>
            </value>
            <value>
                <fullName>3rd Round</fullName>
            </value>
            <value>
                <fullName>Final Round</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Passed 1st Round</fullName>
            </value>
            <value>
                <fullName>Passed 2nd Round</fullName>
            </value>
            <value>
                <fullName>Passed 3rd Round</fullName>
            </value>
            <value>
                <fullName>Passed Final Round</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Years_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_of_Experience__c</fullName>
    <label>Years of Experience</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JobAdvertisement__c/JobAdvertisement__c.object-meta.xml
<CustomObject>
    <label>JobAdvertisement</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>JobAdvertisement  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JobAdvertisements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/JobAdvertisement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JobAdvertisement__c/fields/Years_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_of_Experience__c</fullName>
    <label>Years of Experience</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobApplication.cls
public class JobApplication {
    @AuraEnabled
    public static void createApplication(String jobId, String applicantName, String contact, String email, String experience) {
            Application__c application = new Application__c();
            application.JobAdvertisement__c=jobId;
            application.Applicant_Name__c = applicantName;
            application.Contact_Number__c = contact;
            application.Email_ID__c = email;
            application.Years_of_Experience__c = Decimal.valueOf(experience);
            application.Status__c = 'Applied';
            application.Stage__c  = 'Applied';
            insert application;
        
    }

}