force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <label>Applicant Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/JobAdvertisement__c.field-meta.xml
<CustomField>
    <fullName>JobAdvertisement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>JobAdvertisement</label>
    <referenceTo>JobAdvertisement__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>1st Round</fullName>
            </value>
            <value>
                <fullName>2nd Round</fullName>
            </value>
            <value>
                <fullName>3rd Round</fullName>
            </value>
            <value>
                <fullName>Final Round</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Passed 1st Round</fullName>
            </value>
            <value>
                <fullName>Passed 2nd Round</fullName>
            </value>
            <value>
                <fullName>Passed 3rd Round</fullName>
            </value>
            <value>
                <fullName>Passed Final Round</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Years_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_of_Experience__c</fullName>
    <label>Years of Experience</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JobAdvertisement__c/JobAdvertisement__c.object-meta.xml
<CustomObject>
    <label>JobAdvertisement</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>JobAdvertisement  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JobAdvertisements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/JobAdvertisement__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JobAdvertisement__c/fields/Roles_and_Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Roles_and_Responsibilities__c</fullName>
    <label>Roles and Responsibilities</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/JobAdvertisement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JobAdvertisement__c/fields/Years_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_of_Experience__c</fullName>
    <label>Years of Experience</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JobAdvertisement.cls
public class JobAdvertisement {
    @AuraEnabled(cacheable=true)
    public static List<JobAdvertisement__c> getJobAdvertisements() {
        return [SELECT Id, Job_Title__c, Status__c, Roles_and_Responsibilities__c, Years_of_Experience__c FROM JobAdvertisement__c WHERE Status__c = 'Active'];
    }

    @AuraEnabled
    public static String applyJob(
        Id jobId,
        String applicantName,
        String contactNumber,
        String emailId,
        Decimal experience

    ) {

        try {

            Application__c app =
                new Application__c();

            app.Job_ID_Text__c = jobId;

            app.JobAdvertisement__c = jobId;

            app.Applicant_Name__c =
                applicantName;

            app.Contact_Number__c =
                contactNumber;

            app.Email_ID__c =
                emailId;

            app.Years_of_Experience__c =
                experience;

            app.Status__c = 'Active';

            app.Stage__c = 'Applied';

            app.Is_Archived__c = false;

            insert app;

            System.enqueueJob(
                new JobNotificationQueueable(
                    app.Id
                )
            );

            return 'SUCCESS';

        } catch(Exception ex) {

            throw new AuraHandledException(
                ex.getMessage()
            );
        }
    }


    @AuraEnabled(cacheable=true)
    public static Map<String,
    List<Application__c>>
    getApplications(String emailId) {

        List<Application__c> apps = [

            SELECT Id,
                   Applicant_Name__c,
                   Email_ID__c,
                   Status__c,
                   Stage__c,
                   JobAdvertisement__r.Job_Title__c
            FROM Application__c
            WHERE Email_ID__c = :emailId
            AND Is_Archived__c = false
            ORDER BY CreatedDate DESC
        ];

        Set<String> closedStatuses =
            new Set<String>();

        for(Application_Status_Config__mdt md :
            [

                SELECT DeveloperName,
                       Is_Closed__c
                FROM Application_Status_Config__mdt
            ]) {

            if(md.Is_Closed__c) {

                closedStatuses.add(
                    md.DeveloperName
                );
            }
        }

        List<Application__c>
        activeApps =
        new List<Application__c>();

        List<Application__c>
        inactiveApps =
        new List<Application__c>();

        for(Application__c app : apps) {

            if(closedStatuses.contains(
                app.Status__c
            )) {

                inactiveApps.add(app);

            } else {

                activeApps.add(app);
            }
        }

        Map<String,
        List<Application__c>>
        resultMap =
        new Map<String,
        List<Application__c>>();

        resultMap.put(
            'active',
            activeApps
        );

        resultMap.put(
            'inactive',
            inactiveApps
        );

        return resultMap;
    }

}