force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <label>Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RegistrationHandler.cls
public class RegistrationHandler {
    public static void sendConfirmationEmails(List<Registration__c> newRegistrations) {
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        for(Registration__c reg : newRegistrations){
            if(String.isNotBlank(reg.Email__c)){
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setToAddresses(new String[] { reg.Email__c });
                email.setSubject('Event Registration Confirmation');
                email.setPlainTextBody('Thank you for registering. We will notify you once your participation is confirmed.');
                emails.add(email);
            }
        }

        if(!emails.isEmpty()){
            Messaging.sendEmail(emails);
        }
    }
    
    public static void UpdateStatus(List<Registration__c> reglist,Map<Id,Registration__c> regmap){
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        for(Registration__c reg:reglist){
            if(reg.Status__c != regmap.get(reg.Id).Status__c){
                if(String.isNotBlank(reg.Email__c)){
                   Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                   email.setToAddresses(new String[] { reg.Email__c });
                   email.setSubject('Event Registration Confirmation');
                   email.setPlainTextBody('Your participation has been confirmed.Thank you');
                   emails.add(email);
                }
            }
        }
         if(!emails.isEmpty()){
            Messaging.sendEmail(emails);
        }
    }

}