force-app/main/default/objects/Boat__c/Boat__c.object-meta.xml
<CustomObject>
    <label>Boat</label>
    <nameField>
        <label>Boat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boat__c/fields/BoatType__c.field-meta.xml
<CustomField>
    <fullName>BoatType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BoatType</label>
    <referenceTo>BoatType__c</referenceTo>
    <relationshipLabel>Boats</relationshipLabel>
    <relationshipName>Boats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BoatType__c/BoatType__c.object-meta.xml
<CustomObject>
    <label>BoatType</label>
    <nameField>
        <label>BoatType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoatTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BoatLoader.cls
public with sharing class BoatLoader {
    @AuraEnabled(cacheable=true)
    public static List<BoatType__c> getBoatTypes(){
        List<BoatType__c> boatTypes=[Select Id,Name from BoatType__c];
        return boatTypes;
    }

    @AuraEnabled(cacheable=true)
    public static List<Boat__c> getBoats(){
        List<Boat__c> boats=[Select Id,Name,Price__c,Length__c,Geolocation__Latitude__s,Geolocation__Longitude__s,BoatType__r.Name from Boat__c];
        return boats;
    }
    
    @AuraEnabled(cacheable=true)
    public static Boat__c getBoatDetails(String boatDetailId){
        Boat__c boats=[Select Id,Name,Price__c,Length__c,BoatType__r.Name from Boat__c  WHERE Id = :boatDetailId
        LIMIT 1];
        return boats;
    }


    @AuraEnabled(cacheable=true)
    public static List<Boat__c> getBoatsByType(String boatTypeId){
        List<Boat__c> boatsgallery=[Select Id,Name,Price__c,Length__c,Geolocation__Latitude__s,Geolocation__Longitude__s,BoatType__r.Name from Boat__c where BoatType__c=:boatTypeId];
        return boatsgallery;
    }

    @AuraEnabled
    public static void updateBoats(List<Boat__c> boats) {
        try {
            update boats;
        } catch (Exception e) {
            throw new AuraHandledException('Failed to update boats: ' + e.getMessage());
        }
    }
}